(async()=>{
const $=id=>document.getElementById(id);
let data;
try{const r=await fetch('./songs.json?v=6',{cache:'no-store'});if(!r.ok)throw Error(r.status);data=await r.json()}catch(e){document.body.innerHTML='<main class="app"><h1>songs.jsonを読み込めませんでした</h1></main>';return}
const ui={comboGrid:$('comboGrid'),selectedName:$('selectedName'),selectedChords:$('selectedChords'),selectedStars:$('selectedStars'),practiceChord:$('practiceChord'),practiceNotes:$('practiceNotes'),practiceNext:$('practiceNext'),practiceFill:$('practiceFill'),practiceSequence:$('practiceSequence'),seconds:$('seconds'),practiceSound:$('practiceSound'),practicePlay:$('practicePlay'),practiceReset:$('practiceReset'),publicSongs:$('publicSongs'),songPlayer:$('songPlayer'),songName:$('songName'),songChord:$('songChord'),songNotes:$('songNotes'),songSequence:$('songSequence'),songFill:$('songFill'),songTime:$('songTime'),songPlay:$('songPlay'),songReset:$('songReset'),referenceIntro:$('referenceIntro'),referenceSongs:$('referenceSongs')};
const saved=localStorage.getItem('pianoTrainer.combo.v5');
let combo=data.combinations.find(x=>x.id===saved)||data.combinations[0],pIndex=0,pRunning=false,pStart=0,pRaf=0,ctx=null,audioUnlocked=false,nodes=[],selectedSong=null,songRunning=false,songPlayhead=0,songStartAt=0,songRaf=0;
const stars=n=>'★'.repeat(n)+'☆'.repeat(5-n),chords=()=>combo.chords;
async function ensureAudio(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('Web Audio API unsupported');if(navigator.audioSession){try{navigator.audioSession.type='playback'}catch(e){console.warn(e)}}if(!ctx)ctx=new AC({latencyHint:'interactive'});if(ctx.state==='suspended')await ctx.resume();if(ctx.state!=='running')throw Error('AudioContext did not start');if(!audioUnlocked){const b=ctx.createBuffer(1,1,ctx.sampleRate),s=ctx.createBufferSource();s.buffer=b;s.connect(ctx.destination);s.start();audioUnlocked=true}return ctx}
function midiFromNote(n){const m=/^([A-G])(#|b)?(\d)$/.exec(n);if(!m)return 69;const pc={C:0,D:2,E:4,F:5,G:7,A:9,B:11}[m[1]]+(m[2]==='#'?1:m[2]==='b'?-1:0);return(+m[3]+1)*12+pc}
function freq(n){return 440*2**((midiFromNote(n)-69)/12)}
function stopNodes(){nodes.forEach(n=>{try{n.stop()}catch{}});nodes=[]}
function tone(note,start,dur,vol=.08){if(!ctx||ctx.state!=='running')return;const gain=ctx.createGain(),o=ctx.createOscillator(),o2=ctx.createOscillator(),g2=ctx.createGain();gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(vol,start+.012);gain.gain.exponentialRampToValueAtTime(.0001,start+Math.max(.07,dur*.9));gain.connect(ctx.destination);o.type='triangle';o.frequency.setValueAtTime(freq(note),start);o2.type='sine';o2.frequency.setValueAtTime(freq(note)*2,start);g2.gain.value=.12;o.connect(gain);o2.connect(g2);g2.connect(gain);o.start(start);o2.start(start);o.stop(start+dur);o2.stop(start+dur);nodes.push(o,o2)}
function playChord(name,dur=.8,at=null,vol=.035){if(!ctx||ctx.state!=='running')return;const start=at??ctx.currentTime;(data.chords[name]?.notes||[]).forEach((n,i)=>tone(n,start+i*.018,dur,vol))}
function renderComboGrid(){ui.comboGrid.innerHTML='';data.combinations.forEach(c=>{const b=document.createElement('button');b.className='combo'+(c.id===combo.id?' active':'');b.innerHTML=`<div><div class="comboTop"><span class="stars">${stars(c.rating)}</span><span class="family">${c.family}</span><span class="keyBadge">Key ${c.key}</span></div><div class="comboChords">${c.chords.join(' → ')}</div></div><div class="check">✓</div>`;b.onclick=()=>selectCombo(c.id);ui.comboGrid.appendChild(b)})}
function renderSummary(){ui.selectedName.textContent=`${combo.family} / Key ${combo.key}`;ui.selectedChords.textContent=chords().join(' → ');ui.selectedStars.textContent=stars(combo.rating)}
function renderSequence(el,index){el.innerHTML='';chords().forEach((c,i)=>{const d=document.createElement('div');d.className='seq'+(i===index?' on':'');d.textContent=c;el.appendChild(d)})}
function showPractice(index,progress=0){pIndex=((index%4)+4)%4;const c=chords()[pIndex],nx=chords()[(pIndex+1)%4];ui.practiceChord.textContent=c;ui.practiceNotes.textContent=data.chords[c].jp;ui.practiceNext.textContent=`次：${nx} ／ ${data.chords[nx].jp}`;ui.practiceFill.style.width=Math.max(0,Math.min(1,progress))*100+'%';renderSequence(ui.practiceSequence,pIndex)}
function selectCombo(id){stopPractice();stopSong(true);combo=data.combinations.find(c=>c.id===id)||combo;localStorage.setItem('pianoTrainer.combo.v5',combo.id);pIndex=0;renderComboGrid();renderSummary();showPractice(0);renderReferences()}
function stopPractice(){pRunning=false;cancelAnimationFrame(pRaf);ui.practicePlay.textContent='▶ 開始';stopNodes()}
async function startPractice(){if(pRunning){stopPractice();return}if(ui.practiceSound.value==='on'){try{await ensureAudio()}catch(e){alert('音声を開始できませんでした。もう一度お試しください。');return}}pRunning=true;ui.practicePlay.textContent='Ⅱ 一時停止';pStart=performance.now();if(ui.practiceSound.value==='on')playChord(chords()[pIndex],Math.min(1.6,(+ui.seconds.value||3)*.86));tickPractice()}
function tickPractice(){if(!pRunning)return;const ms=Math.max(.5,+ui.seconds.value||3)*1000,p=(performance.now()-pStart)/ms;showPractice(pIndex,p);if(p>=1){pIndex=(pIndex+1)%4;pStart=performance.now();if(ui.practiceSound.value==='on')playChord(chords()[pIndex],Math.min(1.6,ms/1000*.86))}pRaf=requestAnimationFrame(tickPractice)}
ui.practicePlay.onclick=startPractice;ui.practiceReset.onclick=()=>{stopPractice();pIndex=0;showPractice(0)};ui.practiceSound.onchange=async()=>{if(ui.practiceSound.value==='on'&&pRunning){try{await ensureAudio();playChord(chords()[pIndex],.7)}catch{}}};
function renderPublicSongs(){ui.publicSongs.innerHTML='';data.publicDomainSongs.forEach(s=>{const b=document.createElement('button');b.className='songCard'+(selectedSong?.id===s.id?' active':'');b.innerHTML=`<div class="songHead"><div><div class="songTitle">${s.title}</div><div class="meta">${s.titleEn}<br>${s.credit}</div></div><span class="pill">${s.bpm} BPM</span></div>`;b.onclick=()=>selectPublicSong(s.id);ui.publicSongs.appendChild(b)})}
function songDuration(s){return s.melody.reduce((sum,e)=>sum+e[1],0)*60/s.bpm}
function fmt(sec){sec=Math.max(0,Math.round(sec));return Math.floor(sec/60)+':'+String(sec%60).padStart(2,'0')}
function melodyEvents(s){const spb=60/s.bpm;let beat=0;return s.melody.map(([note,dur])=>{const e={note,start:beat*spb,dur:dur*spb};beat+=dur;return e})}
function harmonyEvents(s){const spb=60/s.bpm;let beat=0;return (s.chordTimeline||[]).map(([chord,dur])=>{const e={chord,start:beat*spb,dur:dur*spb};beat+=dur;return e})}
function harmonyAt(s,sec){const ev=harmonyEvents(s);return ev.find((e,i)=>sec>=e.start&&(sec<e.start+e.dur||i===ev.length-1))||ev[0]}
function renderSongSequence(s,sec){const ev=harmonyEvents(s),current=Math.max(0,ev.findIndex((e,i)=>sec>=e.start&&(sec<e.start+e.dur||i===ev.length-1)));ui.songSequence.innerHTML='';for(let n=0;n<4;n++){const e=ev[Math.min(current+n,ev.length-1)],d=document.createElement('div');d.className='seq'+(n===0?' on':'');d.textContent=e?e.chord:'—';ui.songSequence.appendChild(d)}}
function selectPublicSong(id){stopSong(true);selectedSong=data.publicDomainSongs.find(s=>s.id===id)||null;renderPublicSongs();if(!selectedSong){ui.songPlayer.style.display='none';return}ui.songPlayer.style.display='block';ui.songName.textContent=`${selectedSong.title} · Key ${selectedSong.baseKey} · ${selectedSong.harmonyLabel||'基本伴奏'}`;ui.songTime.textContent=`0:00 / ${fmt(songDuration(selectedSong))}`;songPlayhead=0;showSongAt(0);ui.songFill.style.width='0%'}
function showSongAt(sec){if(!selectedSong)return;const e=harmonyAt(selectedSong,sec),c=e?.chord||'C';ui.songChord.textContent=c;ui.songNotes.textContent=data.chords[c]?.jp||'';renderSongSequence(selectedSong,sec)}
function scheduleSong(from){stopNodes();const s=selectedSong,now=ctx.currentTime+.055;melodyEvents(s).forEach(e=>{if(e.start+e.dur<=from)return;const start=Math.max(e.start,from),trim=start-e.start;tone(e.note,now+start-from,Math.max(.07,e.dur-trim)*.88,.095)});harmonyEvents(s).forEach(e=>{if(e.start+e.dur<=from)return;const start=Math.max(e.start,from),remaining=e.dur-(start-e.start);playChord(e.chord,Math.max(.07,remaining*.92),now+start-from,.027)});songStartAt=ctx.currentTime-from+.055}
async function startSong(){if(!selectedSong)return;if(songRunning){pauseSong();return}try{await ensureAudio()}catch(e){ui.songName.textContent='音声を開始できませんでした';return}if(songPlayhead>=songDuration(selectedSong)-.04)songPlayhead=0;songRunning=true;ui.songPlay.textContent='Ⅱ 一時停止';scheduleSong(songPlayhead);songRaf=requestAnimationFrame(tickSong)}
function pauseSong(){if(!songRunning)return;songPlayhead=Math.max(0,ctx.currentTime-songStartAt);songRunning=false;cancelAnimationFrame(songRaf);stopNodes();ui.songPlay.textContent='▶ 続きから'}
function stopSong(reset=false){if(songRunning&&ctx)songPlayhead=Math.max(0,ctx.currentTime-songStartAt);songRunning=false;cancelAnimationFrame(songRaf);stopNodes();if(reset)songPlayhead=0;ui.songPlay.textContent='▶ 再生'}
function tickSong(){if(!songRunning||!selectedSong||!ctx)return;const total=songDuration(selectedSong);songPlayhead=Math.max(0,ctx.currentTime-songStartAt);if(songPlayhead>=total){songRunning=false;cancelAnimationFrame(songRaf);stopNodes();songPlayhead=0;ui.songPlay.textContent='▶ もう一度';ui.songFill.style.width='100%';ui.songTime.textContent=`${fmt(total)} / ${fmt(total)}`;return}showSongAt(songPlayhead);ui.songFill.style.width=(songPlayhead/total*100)+'%';ui.songTime.textContent=`${fmt(songPlayhead)} / ${fmt(total)}`;songRaf=requestAnimationFrame(tickSong)}
ui.songPlay.onclick=startSong;ui.songReset.onclick=()=>{stopSong(true);if(selectedSong){showSongAt(0);ui.songFill.style.width='0%';ui.songTime.textContent=`0:00 / ${fmt(songDuration(selectedSong))}`}};
function openYouTube(id){const web=`https://www.youtube.com/watch?v=${id}`,isiOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1;if(!isiOS){window.open(web,'_blank','noopener');return}let moved=false;document.addEventListener('visibilitychange',()=>{if(document.hidden)moved=true},{once:true});setTimeout(()=>{if(!moved)location.href=web},850);location.href=`youtube://www.youtube.com/watch?v=${id}`}
function renderReferences(){const list=data.referenceSongs[combo.family]||[];ui.referenceIntro.textContent=`${combo.family}（現在 Key ${combo.key}）の参考曲。YouTubeボタンはiPhoneではアプリ起動を優先します。`;ui.referenceSongs.innerHTML='';if(!list.length){ui.referenceSongs.innerHTML='<div class="empty">参考曲はまだありません。</div>';return}list.forEach(s=>{const d=document.createElement('div');d.className='refCard';d.innerHTML=`<div class="refHead"><div><div class="refTitle">${s.title}</div><div class="meta">${s.artist} · ${s.year}<br>${s.genre}</div></div><span class="pill">${s.year}</span></div><div class="refBottom"><span class="match">${s.match}</span><button class="youtubeBtn">YouTubeで聴く ↗</button></div>`;d.querySelector('button').onclick=()=>openYouTube(s.youtubeId);ui.referenceSongs.appendChild(d)})}
function setTab(name){stopPractice();if(name!=='public')stopSong(false);document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===`panel-${name}`))}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));renderComboGrid();renderSummary();showPractice(0);renderPublicSongs();renderReferences();
})();